
import Head from 'next/head';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <h1 className='text-center mt-3'>CRUD PRACTISE WITH SQL DATABASE</h1>
        <div className='row mt-3'>
          <div className='col-sm-12 col-md-6 col-lg-6 border p-4'>
            <h3 className='text-center pb-3'>Create</h3>
            <div className='wper'>
              <input className='mt-2 mb-2 text-center w-100' type="text" placeholder='Enter your name' />
              <input className='mt-2 mb-2 text-center w-100' type="number" placeholder='Enter your age' />
              <input className='mb-2 mt-2 text-center w-100' type="text" placeholder='Enter your Address' />
              <br />
              <button className='btn text-light bg-success text-center w-100 mt-2 mb-2'>Insert</button>
            </div>
          </div>
          <div className='col-sm-12 col-md-6 col-lg-6 border p-4'>
            <h3 className='text-center pb-3'>Update</h3>
            <div className='wper'>
              <input className='mt-2 mb-2 text-center w-100' type="text" placeholder='Enter your name' />
              <input className='mt-2 mb-2 text-center w-100' type="number" placeholder='Enter your age' />
              <input className='mt-2 mb-2 text-center w-100' type="text" placeholder='Enter your Address' />
              <br />
              <button className='btn text-light bg-success text-center w-100 mt-2 mb-2'>Update</button>
            </div>
          </div>
        </div>
        <div className='row'>
          <div className='col-sm-12 border p-3'>
            <h3 className='text-center'>View Table</h3>
            <div className=' pt-4 h-auto'>
              <table className='table border text-light text-center'>
                <thead>
                  <tr>
                    <td>Sl</td>
                    <td>Name</td>
                    <td>Age</td>
                    <td>Address</td>
                    <td>Action</td>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td>1</td>
                    <td>Md Emon Hossen</td>
                    <td>20</td>
                    <td>Konabari,gazipur,Dhaka,Bangladesh</td>
                    <td className='d-flex justify-content-around'>
                      <button className='btn btn-success'>
                        Edit
                      </button>
                      <button className='btn btn-danger'>
                        Delete
                      </button>
                    </td>
                  </tr>
                  <tr>
                    <td>2</td>
                    <td>Imran Hossen Jowel</td>
                    <td>24</td>
                    <td>Konabari,gazipur,Dhaka,Bangladesh</td>
                    <td className='d-flex justify-content-around'>
                      <button className='btn btn-success'>
                        Edit
                      </button>
                      <button className='btn btn-danger'>
                        Delete
                      </button>
                    </td>
                  </tr>
                  <tr>
                    <td>3</td>
                    <td>Md Alamin Hossen</td>
                    <td>6</td>
                    <td>Konabari,gazipur,Dhaka,Bangladesh</td>
                    <td className='d-flex justify-content-around'>
                      <button className='btn btn-success'>
                        Edit
                      </button>
                      <button className='btn btn-danger'>
                        Delete
                      </button>
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </main>
    </>
  )
}
